"""
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""



__author__ = "Felipe Sasso"

def fib(n):
	if n < 2:
		return n
	else:
		return fib(n - 1) + fib(n - 2)

sum = 0
term = 1
curterm = 0
while curterm < 4000000:
	curterm = fib(term);
	if(curterm % 2 == 0):
		sum+= curterm
	term += 1

print sum
